<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2788" started-at="2019-10-22T18:27:10Z" finished-at="2019-10-22T18:27:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2788" started-at="2019-10-22T18:27:10Z" finished-at="2019-10-22T18:27:13Z">
      <class name="samplerest.WorkingRestClass">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:samplerest.WorkingRestClass@68ceda24]" name="beforeClass" is-config="true" duration-ms="1940" started-at="2019-10-22T18:27:10Z" finished-at="2019-10-22T18:27:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="soapUIRestTestRunner()[pri:0, instance:samplerest.WorkingRestClass@68ceda24]" name="soapUIRestTestRunner" duration-ms="819" started-at="2019-10-22T18:27:12Z" finished-at="2019-10-22T18:27:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual matches expected expected [Michaela] but found [Michael]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual matches expected expected [Michaela] but found [Michael]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at samplerest.WorkingRestClass.soapUIRestTestRunner(WorkingRestClass.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- soapUIRestTestRunner -->
      </class> <!-- samplerest.WorkingRestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
